;; This logfile was generated automatically by `xindy'
;; at 10.01.2017  04:17:35
;; Indexstyle: "/tmp/NVeg96P7Lm", Rawindex: "/tmp/RJfuWknEdQ", Output: "thesis.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "´¨ÐÚ—¼ „—œÃË— Ú€´®" -> "L"
Letter-group: "€†®" -> "A"
Letter-group: "€È¨" -> "A"
Letter-group: "Úà¼" -> "T"
Letter-group: "Ðœ" -> "S"
Letter-group: "€Ë" -> "A"
Letter-group: "È—Ë" -> "P"
Letter-group: "¨ÃÚ" -> "I"
Letter-group: "´ÃË€æ€¼" -> "L"
Letter-group: "´Èæ€¼" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€†®" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¨ÃÚ" -> "I"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´¨ÐÚ—¼ „—œÃË— Ú€´®" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "È—Ë" -> "P"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ðœ" -> "S"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Úà¼" -> "T"
WARNING: location-reference "{}{i}" did match multiple location-classes! (taking first one)
WARNING: location-reference "{}{x}" did match multiple location-classes! (taking first one)

makeglossaries messages:

Cannot locate xindy module for language spanish in codepage utf8.
Retrying using default codepage.
Cannot locate xindy module for language spanish.
Retrying with -L general
